Update main.py
Ved-programmer/TypingPro pull request #30
Opened 2021-01-22 15:25 UTC by smartnavdeep

Adding the LICENCE links to the screen

As I said open source is open source, meant to be copied,

I was just exploring repositories on github and then I have found that many repositories do like this in their code..
![Screenshot 2021-01-22 204917](https://user-images.githubusercontent.com/65970997/105509356-6b2f4380-5cf3-11eb-92d5-143827ad158f.png)

Notice what happened ? the licence information is included in the code, so even if some one copies you code he can't restrict the rules of licence, and then the information of the licence lies over there, usually in the top or the bottom of the script,

I could have kept it in the top of the python script but the import statements should always be on top, it is a pyflakes/python grammar.

Hope this PR help you.

---

Regards, 
Navdeep

2021-01-22 16:23 UTC, Ved-programmer requested changes

2021-01-22 16:23 UTC, Ved-programmer commented on TypingPro/main.py
> +Licensed under MIT (https://github.com/Ved-Programmer/TypingPro/blob/master/LICENSE)
Show we include a link to the license or just include the license itself? I am thinking that including the actual MIT License inside the script could have a disadvantage of not being up to date. We would have to keep updating the license in the code if we ever want to change the license type of license year or modify the license for any reason. Plus if someone has downloaded the code and we change the license the later then the downloaded version of the code would have the outdated license. This is a disadvantage however, the advantage is that the license would be there in the code always, it doesn't matter if we delete this repository or something like that. The license would stay there forever. It all will be in one location. So, if someone wants to see the license then the person can just read it right in the code. I am kind of confused which solution would be better, what do you think, I would like your opinion on that. Should we include the license itself or just a link to the license.

2021-01-23 07:08 UTC, smartnavdeep commented
I didn't get that just by adding the link of the LICENCE file, there might be any disadvantages, and even if we change the licence, the link to that file of the licence will always remain the same, unless we rename the file, also coed needs to be code, adding licence may increase the size of the file, so if you wish so then please give a confirmation request and I will make a PR

Regards,
Navdeep.

2021-01-23 07:12 UTC, Ved-programmer commented
I guess that both the solution have pros and cons. I guess we should just include the link to the license. I am merging this pull request.

2021-01-23 07:12 UTC, merged

2021-01-23 07:24 UTC, smartnavdeep commented
Yeah sure.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Ved Rathi<mailto:notifications@github.com>
Sent: Saturday, January 23, 2021 12:42 PM
To: Ved-programmer/TypingPro<mailto:TypingPro@noreply.github.com>
Cc: Navdeep Kante<mailto:kantenavdeep@outlook.com>; Author<mailto:author@noreply.github.com>
Subject: Re: [Ved-programmer/TypingPro] Update main.py (#30)


I guess that both the solution have pros and cons. I guess we should just include the link to the license. I am merging this pull request.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Ved-programmer/TypingPro/pull/30#issuecomment-765881187>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/APXKGNNXTA7665R4B62EAELS3JZFHANCNFSM4WOUNPEQ>.

2021-01-29 04:23 UTC, Ved-programmer commented on TypingPro/main.py
> +Licensed under MIT (https://github.com/Ved-Programmer/TypingPro/blob/master/LICENSE)
we ended up adding the link

2021-01-29 04:23 UTC, Ved-programmer reviewed
added the final output